# Generated by Django 3.2.9 on 2021-11-10 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0002_auto_20211110_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booksApp.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booksApp.subcategory'),
        ),
    ]
