# Generated by Django 3.2.9 on 2021-11-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0003_auto_20211110_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='addedBy',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='lastModifiedBy',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='addedBy',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='lastModifiedBy',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
