# Generated by Django 3.2.9 on 2021-11-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0004_auto_20211110_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='addedBy',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='lastModifiedBy',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
