# Generated by Django 3.2.9 on 2021-11-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0005_auto_20211110_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='lastModifiedBy',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lastModifiedOn',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='lastModifiedBy',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='lastModifiedOn',
        ),
    ]
